### PR TITLE
#5 make MemcacheService pluggable

### PR DESCRIPTION
**Pull request by gabor-farkas**
I mainly adapted the patterns from Objectify 6

---
This change is [Reviewable](https://reviewable.io/reviews/aliz-ai/objectify/6)

### CODE REVIEW

**Review by ttozser — APPROVED** [review]

**Review by nbali — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/objectify/6)* status: all files reviewed, 8 unresolved discussions (waiting on @gabor-farkas)

___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 64 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx0ps14lRuppUGmO_:-MKjx0ps14lRuppUGmOa:b-abqih9) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L64)):*
> ```Java
> 
> 	/** Override this if you need special behavior from your EntityMemcache */
> 	protected EntityMemcache createEntityMemcache() {
> ```

you could override this, not anymore
___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 73 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx8sL4mjF6xeCAJ6O:-MKjx8sL4mjF6xeCAJ6P:bh8vk8) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L73)):*
> ```Java
> 	public ObjectifyFactory(MemcacheService memcacheService) {
> 		this.memcache = memcacheService;
> 		entityMemcache = memcacheService == null ? null : new EntityMemcache(memcacheService, MEMCACHE_NAMESPACE, new CacheControlImpl(this), this.memcacheStats);
> ```

it's strange to me, you can replace one of the fields, and keep the other (initialize the factory, then replace the memcache, but entity memcache stays)
___
*[src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java, line 19 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjyMPb13NXvnkNV-2j:-MKjyMPb13NXvnkNV-2k:bshdhx2) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java#L19)):*
> ```Java
>  * @author Jeff Schnitzer <jeff@infohazard.org>
>  */
> public class CachingDatastoreServiceFactory
> ```

why was this removed? the CachingDatastoreService is still around
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 24 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxK0Z9qmeTHkw6mfD:-MKjxK0Z9qmeTHkw6mfE:b5241rd) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L24)):*
> ```Java
> import com.google.appengine.spi.ServiceFactoryFactory;
> import com.google.common.base.Objects;
> ```

formatter ;)
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 163 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxXYo-2e3eTCJvPxj:-MKjxXYo-2e3eTCJvPxk:b7ifuy4) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L163)):*
> ```Java
> 	public EntityMemcache(
> 			MemcacheService memcacheService,
> 			String namespace,
> ```

keeping the namespace parameter around is a bad idea, as it was originally used to provide the memcache with the proper namespace... now that happens externally, so namespace parameter is useless
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 188 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxiiG6JOabXMUIDGw:-MKjxiiG6JOabXMUIDGx:b-u2u9st) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L188)):*
> ```Java
> 	{
> 		this.memcache = new KeyMemcacheService(memcacheService);
> 		this.memcache.setErrorHandler(ErrorHandlers.getConsistentLogAndContinue(Level.SEVERE));
> ```

I would add this to the default GAE adapter
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheService.java, line 16 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjvglODV5Q9A1voTZ2:-MKjvglODV5Q9A1voTZ3:b4h1j39) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/MemcacheService.java#L16)):*
> ```Java
>  * takes care of translating it to something that can be stored.
>  */
> public interface MemcacheService {
> ```

I would add javadoc, that it has been copied from/based on (then link to specific file at specific version) (and assume I wrote to every copied file)
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java, line 39 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjy94M25KQB7t1d4LO:-MKjy94M25KQB7t1d4LP:b-dyua3e) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java#L39)):*
> ```Java
> 	public static MemcacheService createProxy(MemcacheService raw, int retryCount)
> 	{
> 		raw.setErrorHandler(ErrorHandlers.getStrict());
> ```

add to gae adapter?

**Review by gabor-farkas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/objectify/6)* status: all files reviewed, 8 unresolved discussions (waiting on @nbali)

___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 64 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx0ps14lRuppUGmO_:-MKnRkH06d-T4fIDne2s:bqtpen6) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L64)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

you could override this, not anymore
</blockquote></details>

As I mentioned in the commit message, I followed the solution applied in Objectify 6.
The design there is that you can specify your own MemcacheService, but not EntityMemcache. EntityMemcache is actually written in a way that it cannot easily be meaningfully specialized or replaced by extending it. For example, the its Bucket class is used outside EntityMemcache, but many of the logic there is not easily replaceable.
As seen in ofy6, the design is such that EntityMemcache is considered as a core part of objectify itself, and the caching-related part is behind the new MemcacheService interface.
___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 73 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx8sL4mjF6xeCAJ6O:-MKnSVAH9-OhNe1C0qUA:b-z8j252) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L73)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

it's strange to me, you can replace one of the fields, and keep the other (initialize the factory, then replace the memcache, but entity memcache stays)
</blockquote></details>

where can you replace the memcache after initializing the factory?
___
*[src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java, line 19 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjyMPb13NXvnkNV-2j:-MKnSbNH2zPaG5RmMwbr:b-vc7xk2) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java#L19)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

why was this removed? the CachingDatastoreService is still around
</blockquote></details>

This factory was only used by testcases, and again, I followed what was done in ofy6.
The problem with this static factory was that with the new replaceable memcache you can no longer statically construct an EntityMemcache.
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 24 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxK0Z9qmeTHkw6mfD:-MKnT7dG0FbGtMd07wBQ:b-x7juv3) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L24)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

formatter ;)
</blockquote></details>

This is actually the right import order, I messed it up in a previous PR.
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 163 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxXYo-2e3eTCJvPxj:-MKnTv7d5Chy6Z-04n6I:b-bkipiu) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L163)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

keeping the namespace parameter around is a bad idea, as it was originally used to provide the memcache with the proper namespace... now that happens externally, so namespace parameter is useless
</blockquote></details>

That's right, I forgot to remove that.
Note that ofy6 even assigns this to an unused field https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L163  - and I was trying to make this as similar to ofy6 as possible, but indeed, this parameter is even misleading.
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 188 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxiiG6JOabXMUIDGw:-MKnUF8v8Bs0ql4NQfT-:bvo1q93) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L188)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I would add this to the default GAE adapter
</blockquote></details>

Why?
Users of objectify with the legacy gae cache can provide their custom error handlers to the bare MemcacheService they construct the adapter with.
In my understanding, this customization mechanism here was needed because the memcacheservice was constructed inside objectify.
Now that it's constructed by the configurator, they can customize it as they wish.
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheService.java, line 16 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjvglODV5Q9A1voTZ2:-MKnUrkZ3Q7BPltP8YIn:b-k6hzuv) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/MemcacheService.java#L16)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I would add javadoc, that it has been copied from/based on (then link to specific file at specific version) (and assume I wrote to every copied file)
</blockquote></details>

Why would I do that? What woud be the benefit?
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java, line 39 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjy94M25KQB7t1d4LO:-MKnUwkV-VB9dkZYGBtg:b2nhky0) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java#L39)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

add to gae adapter?
</blockquote></details>

No.

**Review by nbali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/objectify/6)* status: all files reviewed, 7 unresolved discussions (waiting on @gabor-farkas and @nbali)

___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 64 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx0ps14lRuppUGmO_:-MLU5sr5DmsKPI_IqgZi:bqx5gpn) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L64)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

As I mentioned in the commit message, I followed the solution applied in Objectify 6.
The design there is that you can specify your own MemcacheService, but not EntityMemcache. EntityMemcache is actually written in a way that it cannot easily be meaningfully specialized or replaced by extending it. For example, the its Bucket class is used outside EntityMemcache, but many of the logic there is not easily replaceable.
As seen in ofy6, the design is such that EntityMemcache is considered as a core part of objectify itself, and the caching-related part is behind the new MemcacheService interface.
</blockquote></details>

I don't think I ever tried to do that, but if I would have and I would a custom implementation+override I would be pissed at you
___
*[src/main/java/com/googlecode/objectify/ObjectifyFactory.java, line 73 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjx8sL4mjF6xeCAJ6O:-MLU-E7V-c3WJl7Z7eLA:b-ujuvxx) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/ObjectifyFactory.java#L73)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

where can you replace the memcache after initializing the factory?
</blockquote></details>

it's a protected not final field, pretty much anywhere you want
___
*[src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java, line 19 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjyMPb13NXvnkNV-2j:-MLU6DBV9_bNSRdjEcKT:b-wjeaix) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/CachingDatastoreServiceFactory.java#L19)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

This factory was only used by testcases, and again, I followed what was done in ofy6.
The problem with this static factory was that with the new replaceable memcache you can no longer statically construct an EntityMemcache.
</blockquote></details>

1. ok
2. there were methods with input entity memcache
___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 188 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxiiG6JOabXMUIDGw:-MLU510t6rHgU_WikyQf:b2ci9c2) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L188)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

Why?
Users of objectify with the legacy gae cache can provide their custom error handlers to the bare MemcacheService they construct the adapter with.
In my understanding, this customization mechanism here was needed because the memcacheservice was constructed inside objectify.
Now that it's constructed by the configurator, they can customize it as they wish.
</blockquote></details>

if I would start using this code I would expect to have a drop-in legacy gae memcache available that has exactly the same behaviour as it did before, that is why I said the default gae version should have this
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheService.java, line 16 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjvglODV5Q9A1voTZ2:-MLU5JwADqK54d49kwsI:b-hkg49b) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/MemcacheService.java#L16)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

Why would I do that? What woud be the benefit?
</blockquote></details>

helping the reviewer, and the future maintainer
___
*[src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java, line 39 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjy94M25KQB7t1d4LO:-MLU5TeP7yfaSX1egvYw:b-uctd6o) ([raw file](https://github.com/aliz-ai/objectify/blob/644b5b2337bdc91f055add52f3a5a7dcfb00fd69/src/main/java/com/googlecode/objectify/cache/MemcacheServiceRetryProxy.java#L39)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

No.
</blockquote></details>

changed behaviour for legacy code and a retry proxy makes absolutely completely zero sense, if the wrapped memcache doesn't have an error handler that actually fails

**Review by nbali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/objectify/6)* status: all files reviewed, 7 unresolved discussions (waiting on @gabor-farkas)

___
*[src/main/java/com/googlecode/objectify/cache/EntityMemcache.java, line 163 at r1](https://reviewable.io/reviews/aliz-ai/objectify/6#-MKjxXYo-2e3eTCJvPxj:-MLU73E02uxjQ5IYGc8q:b3ksm) ([raw file](https://github.com/aliz-ai/objectify/blob/b952cafa9d0dbf7bb290120b8586338a623d846c/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L163)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

That's right, I forgot to remove that.
Note that ofy6 even assigns this to an unused field https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L163  - and I was trying to make this as similar to ofy6 as possible, but indeed, this parameter is even misleading.
</blockquote></details>

k

**Pull request merged**
